deployment:
  tasks:
    - export DEPLOYPATH=/home2/nswbnorg/public_html
    - /usr/local/bin/node /usr/local/bin/npm install
    - /usr/local/bin/node /usr/local/bin/npm run build
    - rsync -a build/ $DEPLOYPATH/
