deployment:
  tasks:
    - export DEPLOYPATH=/home2/nswbnorg/public_html
    - /usr/local/bin/node /usr/local/bin/npm install
    - /usr/local/bin/node /usr/local/bin/npm run build
    - curl -T ./build/* ftp://ftp.nswbn.org/$DEPLOYPATH/ --user $FTP_USERNAME:$FTP_PASSWORD
