name: Deploy NSWBN Website to cPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 🛠 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 📦 Install dependencies
        working-directory: ./
        run: npm install

      - name: 🔨 Build the React.js app
        working-directory: ./
        run: npm run build

      - name: 📂 Sync folders and files to the server via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}      
          username: ${{ secrets.FTP_USERNAME }}   
          password: ${{ secrets.FTP_PASSWORD }}   
          server-dir: /home2/nswbnorg/public_html/
          local-dir: './dist/'  
